version: 2.1
jobs:
  lint:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v3.1.0
    steps:
      - checkout
      - run:
          command: helm init --stable-repo-url=https://charts.helm.sh/stable --client-only
          working_directory: charts
      - run: ct lint --config .circleci/chart-testing.yaml --lint-conf .circleci/lintconf.yaml
workflows:
  version: 2
  workflow:
    jobs:
      - lint
